name 'puppetlabs-motd'
version '1.0.1'

author 'puppetlabs'
license 'Apache License, Version 2.0'
project_page 'https://github.com/puppetlabs/puppetlabs-motd'
source 'git@github.com:puppetlabs/puppetlabs-motd.git'
summary 'A simple module to demonstrate managing /etc/motd as a template'
description 'This module simply manages /etc/motd as a template, showing interpolation of system attributes'
